import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MyButton from './components/Buttom'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Formulario</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.titulo}>
        <h1>Titulo Formulario</h1>
      </main>
      <div className={styles.cajon}>
        <h2>Datos</h2>
        <div className={styles.cajonFormulario}>
          <h2>Informe anónimos</h2>
          <form action="/api/form" method="post"> ¿Cúal es tu clasificacion del reporte?
            <ul>
              <li><p>Asedio moral<input required type="radio" name="op" value="op1" /></p></li>
              <li><p>Acoso sexual<input required type="radio" name='op' value="op2" /></p></li>
              <li><p>Siniestro automovilistico<input required type="radio" name="op" value="op3" /></p></li>
            </ul>
              <p>Informes:</p>
            <div><textarea required name="textarea" rows="10" cols="50" placeholder="Escribe tu Informe"></textarea></div>
     
            <p>Selecciones los posibles acontecimientos</p>
            <ol>
              <li>Daños psicologicos</li>
              <li>Agresion Fisica</li>
              <li >Choque (consecuensias traumaticas Leves)</li>
              <li >Choque (Consecuencias traumaticas Graves)</li>
            </ol>
            <p>Estado de Salud de los Involucrados</p>
            <p>Vivo<input  required type="radio" name="salud" value="Vivo" /></p>
            <p>Medio-vivo<input  required type="radio" name="salud" value="Medio-vivo" /></p>
            <p>Muerto <input  required type="radio" name="salud" value="Muerto" /></p>
            <MyButton/>
          </form>
        </div>
      </div>
    </div>
  )
}
